version: "3"

services:
    mongo:
        container_name: mongodb
        image: mongo:6.0.3
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: Cross19950502
        ports:
            - "27017:27017"
        volumes:
            - ./database/db:/data/db
        # logging:
        #   driver: none

    backendNote:
        container_name: noteBackend
        image: note_backend:1.0
        restart: always
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            MONGO_URI: mongodb://root:Cross19950502@mongo/Note
            SECRET_KEY: TeWO@aM&e/%oV_p%
        links:
            - mongo
